name: Add CNAME file

on:
  push:
    branches:
      - main  # Change this to the appropriate branch name if needed

jobs:
  add_cname:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create CNAME file
        run: |
          echo "admida0ui.tech" > CNAME

      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add CNAME
          git commit -m "Add CNAME file" || true
          git push